# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dehs-M276sGdg6ScHDXrC46TUS6qbe3V
"""

!pip install 'qiskit[visualization]' qiskit-ibm-runtime qiskit-aer qiskit-experiments
# Core Qiskit imports
from qiskit import QuantumCircuit
from qiskit.visualization import plot_histogram
from qiskit_aer import AerSimulator
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager

# IBM Runtime specific imports
from qiskit_ibm_runtime import SamplerV2 as Sampler, QiskitRuntimeService

import numpy as np


from qiskit_experiments.test.mock_iq_backend import MockIQBackend
from qiskit_experiments.test.mock_iq_helpers import MockIQT1Helper
from qiskit_experiments.data_processing import DataProcessor, nodes
from qiskit_experiments.library import T1


backend = MockIQBackend(MockIQT1Helper(t1=90e-6, iq_cluster_centers=[((-1, 1), (1, 1))]))

exp = T1(
    physical_qubits=(0,),
    backend=backend,
    delays=np.linspace(0, 400e-6, 21),
)

exp_data = exp.run()
display(exp_data.analysis_results(dataframe=True).iloc[0])

"""### T2 Decoherence Time Experiment"""

# T2 Experiment Imports
from qiskit_experiments.library import T2Ramsey

# Define delays for the T2 experiment
t2_delays = np.linspace(0, 400e-6, 21)

# Instantiate the T2Ramsey experiment
exp_t2 = T2Ramsey(
    physical_qubits=(0,),
    backend=backend,
    delays=t2_delays,
    osc_freq=2e6 # Add an oscillation frequency to clearly observe Ramsey fringes
)

# Run the T2 experiment
exp_data_t2 = exp_t2.run()

# Display the analysis results for T2
display(exp_data_t2.analysis_results(dataframe=True).iloc[0])

analysis_results_t2 = exp_data_t2.analysis_results(dataframe=False)

t2_decay_constant = None
for result in analysis_results_t2:
    if result.name == 'T2star': # Changed from 't2ramsey' to 'T2star'
        t2_decay_constant = result.value
        break

if t2_decay_constant:
    print(f"Extracted T2 decay constant (T2star): {t2_decay_constant}")
else:
    print("T2 decay constant (parameter 'T2star') not found.")
    print("Available analysis results:")
    for result in analysis_results_t2:
        display(result)

import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import pandas as pd
import numpy as np

# --- Manual extraction of processed data points from raw experiment data for T2 ---
raw_data_list_t2 = exp_data_t2.data()
df_raw_t2 = pd.DataFrame(raw_data_list_t2)

# Reuse the function for extracting P(0), its standard error, and xval
extracted_data_t2 = df_raw_t2.apply(extract_p0_and_error_and_xval, axis=1)

# Extract delays, processed_y_data, and y_errors for T2
delays_t2 = extracted_data_t2['xval'].values
processed_y_data_t2 = extracted_data_t2['p0'].values
y_errors_t2 = extracted_data_t2['std_err_p0'].values

# Ensure y_errors has no zeros or NaNs for curve_fit
y_errors_t2[y_errors_t2 == 0] = np.finfo(float).eps
y_errors_t2[np.isnan(y_errors_t2)] = np.finfo(float).eps

# Define the T2Ramsey fit function
def t2_ramsey_fit_func(t, A, T2star, freq, phi, B):
    return A * np.exp(-t / T2star) * np.cos(2 * np.pi * freq * t + phi) + B

# Get analysis results for initial guesses
fit_result_t2star = None
fit_result_freq = None
for result in analysis_results_t2:
    if result.name == 'T2star':
        fit_result_t2star = result
    elif result.name == 'Frequency':
        fit_result_freq = result

# Initial guess for parameters (A, T2star, freq, phi, B)
# A: Amplitude, typically start_val - end_val
initial_guess_A_t2 = processed_y_data_t2[0] - processed_y_data_t2[-1]
# B: Offset, typically end_val
initial_guess_B_t2 = processed_y_data_t2[-1]

# T2star: from the fit_result if available, otherwise a rough guess
initial_guess_T2star = fit_result_t2star.value.nominal_value if fit_result_t2star and fit_result_t2star.value.nominal_value > 0 else np.max(delays_t2) / 3
if initial_guess_T2star <= 0: # Ensure T2star is positive
    initial_guess_T2star = np.max(delays_t2) / 3

# Freq: from the fit_result if available, otherwise use osc_freq from experiment setup
initial_guess_freq = fit_result_freq.value.nominal_value if fit_result_freq else exp_t2.experiment_options.osc_freq

# Phi: Phase, typically around 0 or pi/2
initial_guess_phi = 0.0

p0_t2 = [initial_guess_A_t2, initial_guess_T2star, initial_guess_freq, initial_guess_phi, initial_guess_B_t2]

# Perform the curve fit
try:
    popt_t2, pcov_t2 = curve_fit(t2_ramsey_fit_func, delays_t2, processed_y_data_t2, p0=p0_t2, sigma=y_errors_t2, absolute_sigma=True, maxfev=5000)
    A_t2, T2star_value, freq_value, phi_value, B_t2 = popt_t2
except RuntimeError as e:
    print(f"Error during T2Ramsey curve fitting: {e}")
    # Fallback if fitting fails, perhaps raise an error or use default values
    raise

# Calculate fitted values using the delays and fit parameters
fitted_y_data_t2 = t2_ramsey_fit_func(delays_t2, A_t2, T2star_value, freq_value, phi_value, B_t2)

# Plotting T2Ramsey data and fit
plt.figure(figsize=(10, 6))
plt.errorbar(delays_t2, processed_y_data_t2, yerr=y_errors_t2, fmt='o', label='Experimental Data', capsize=3)
plt.plot(delays_t2, fitted_y_data_t2, 'r-', label=f'Fit: A={A_t2:.2f}, T2*={T2star_value*1e6:.2f}μs, Freq={freq_value/1e6:.2f}MHz, Φ={phi_value:.2f}, B={B_t2:.2f}')
plt.xlabel('Delay (s)')
plt.ylabel('Population of State 0 (P(0))')
plt.title('T2Ramsey Experiment Data and Fit')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Calculate residuals for T2Ramsey
residuals_t2 = processed_y_data_t2 - fitted_y_data_t2

# Plot residuals for T2Ramsey
plt.figure(figsize=(8, 5))
plt.errorbar(delays_t2, residuals_t2, yerr=y_errors_t2, fmt='o', label='Residuals', capsize=3)
plt.axhline(0, color='r', linestyle='--', label='Zero Residuals')
plt.xlabel("Delay (s)")
plt.ylabel("Residuals (Signal)")
plt.title("T2Ramsey Experiment Fit Residuals")
plt.legend()
plt.grid(True)
plt.show()

# Calculate Chi-squared and Reduced Chi-squared for T2Ramsey
chi_squared_t2 = np.sum(((processed_y_data_t2 - fitted_y_data_t2) / y_errors_t2)**2)

# Number of data points (N)
num_data_points_t2 = len(processed_y_data_t2)
# Number of parameters in the T2Ramsey fit (A, T2star, freq, phi, B) = 5
num_parameters_t2 = len(popt_t2)

# Degrees of freedom (dof) = N - num_parameters
degrees_of_freedom_t2 = num_data_points_t2 - num_parameters_t2

reduced_chi_squared_t2 = chi_squared_t2 / degrees_of_freedom_t2

print(f"Chi-squared value for T2Ramsey: {chi_squared_t2:.4f}")
print(f"Degrees of freedom for T2Ramsey: {degrees_of_freedom_t2}")
print(f"Reduced Chi-squared value for T2Ramsey: {reduced_chi_squared_t2:.4f}")

!pip install emcee corner

"""Now, let's import the necessary libraries and define the log-prior, log-likelihood, and log-probability functions required for the MCMC sampler. The `log_prior` function defines our beliefs about the parameters before seeing the data, and the `log_likelihood` connects our model to the observed data, taking into account the measurement errors."""

import emcee
import corner

# Define the log-prior function, now accepting T2star prior bounds
def log_prior(params, t2star_min, t2star_max):
    A, T2star, freq, phi, B = params
    # Prior for A: Uniform between -2 and 2 (amplitude)
    if not -2 < A < 2: return -np.inf
    # Prior for T2star: Uniform between specified min/max
    if not t2star_min < T2star < t2star_max: return -np.inf
    # Prior for freq: Uniform around the expected frequency range
    if not 0 < freq < 5e6: return -np.inf # e.g., 0 to 5 MHz
    # Prior for phi: Uniform between -pi and pi
    if not -np.pi < phi < np.pi: return -np.inf
    # Prior for B: Uniform between -2 and 2 (offset)
    if not -2 < B < 2: return -np.inf

    return 0.0 # Return 0 for a flat prior within the bounds

# Define the log-likelihood function (remains unchanged)
def log_likelihood(params, x, y, yerr):
    A, T2star, freq, phi, B = params
    model = t2_ramsey_fit_func(x, A, T2star, freq, phi, B)
    # Assuming Gaussian errors, the log-likelihood is:
    return -0.5 * np.sum(((y - model) / yerr)**2 + np.log(2 * np.pi * yerr**2))

# Define the log-probability function, now passing T2star prior bounds to log_prior
def log_prob(params, x, y, yerr, t2star_min, t2star_max):
    lp = log_prior(params, t2star_min, t2star_max)
    if not np.isfinite(lp): # If prior is -inf, then posterior is -inf
        return -np.inf
    return lp + log_likelihood(params, x, y, yerr)

"""Now we'll set up and run the `emcee` sampler. We need to define the number of walkers, the number of dimensions (parameters), and provide initial positions for the walkers. We'll use the least-squares fit results (`popt_t2`) as a starting point, with a small perturbation for each walker."""

n_dim = len(popt_t2)  # Number of parameters (A, T2star, freq, phi, B)
n_walkers = 32     # Number of MCMC walkers (should be >= 2*n_dim)
n_steps = 5000   # Number of MCMC steps

# Initial positions for walkers: start near the least-squares fit results
# Perturb each parameter slightly for each walker
pos = popt_t2 + 1e-4 * np.random.randn(n_walkers, n_dim)

# Ensure T2star initial guesses are positive
pos[:, 1] = np.abs(pos[:, 1])

sampler = emcee.EnsembleSampler(n_walkers, n_dim, log_prob, args=(delays_t2, processed_y_data_t2, y_errors_t2))

print("Running MCMC...")
sampler.run_mcmc(pos, n_steps, progress=True)
print("MCMC finished.")

"""After running the sampler, we'll discard the 'burn-in' phase of the chains and then flatten them to obtain the posterior samples. These samples represent the probability distribution of our parameters given the data and our priors. We can then use these samples to estimate the median values and credible intervals for each parameter."""

# Discard burn-in samples and flatten the chain
flat_samples = sampler.get_chain(discard=1000, thin=15, flat=True)

# Calculate median and 1-sigma credible intervals for each parameter
labels = ["A", "T2star", "freq", "phi", "B"]
corner_results = []

print("Bayesian Fit Results (Median and 1-sigma credible intervals):")
for i in range(n_dim):
    mcmc = np.percentile(flat_samples[:, i], [16, 50, 84])
    q = np.diff(mcmc)
    txt = f"{labels[i]} = {mcmc[1]:.4e} (+{q[1]:.2e} / -{q[0]:.2e})"
    print(txt)
    corner_results.append(mcmc[1])

# Plot the corner plot to visualize posterior distributions and correlations
fig = corner.corner(flat_samples, labels=labels, quantiles=[0.16, 0.5, 0.84], show_titles=True, title_kwargs={"fontsize": 12})
plt.suptitle("Posterior Distributions for T2Ramsey Parameters", fontsize=16)
plt.show()

"""Finally, let's compare the T2* value and its uncertainty from the least-squares fit (`scipy.optimize.curve_fit`) with the Bayesian estimate. We'll also plot the Bayesian fit against the data and compare the residuals."""

A_bayes, T2star_bayes, freq_bayes, phi_bayes, B_bayes = corner_results

# Calculate fitted values using the Bayesian fit parameters
fitted_y_data_bayes = t2_ramsey_fit_func(delays_t2, A_bayes, T2star_bayes, freq_bayes, phi_bayes, B_bayes)

# Plotting T2Ramsey data and Bayesian fit
plt.figure(figsize=(10, 6))
plt.errorbar(delays_t2, processed_y_data_t2, yerr=y_errors_t2, fmt='o', label='Experimental Data', capsize=3)
plt.plot(delays_t2, fitted_y_data_bayes, 'g-', label=f'Bayesian Fit: A={A_bayes:.2f}, T2*={T2star_bayes*1e6:.2f}μs, Freq={freq_bayes/1e6:.2f}MHz, Φ={phi_bayes:.2f}, B={B_bayes:.2f}')
plt.plot(delays_t2, fitted_y_data_t2, 'r--', label=f'LS Fit: T2*={T2star_value*1e6:.2f}μs (for comparison)', alpha=0.7)
plt.xlabel('Delay (s)')
plt.ylabel('Population of State 0 (P(0))')
plt.title('T2Ramsey Experiment Data and Bayesian Fit')
plt.legend()
plt.grid(True)
plt.show()

# Calculate and plot residuals for Bayesian fit
residuals_bayes = processed_y_data_t2 - fitted_y_data_bayes

plt.figure(figsize=(8, 5))
plt.errorbar(delays_t2, residuals_bayes, yerr=y_errors_t2, fmt='o', label='Bayesian Residuals', capsize=3)
plt.axhline(0, color='r', linestyle='--', label='Zero Residuals')
plt.xlabel("Delay (s)")
plt.ylabel("Residuals (Signal)")
plt.title("T2Ramsey Experiment Bayesian Fit Residuals")
plt.legend()
plt.grid(True)
plt.show()

print("\n--- Comparison Summary ---")
print(f"Least-Squares T2* value: {T2star_value*1e6:.2f} μs")
print(f"Bayesian Median T2* value: {T2star_bayes*1e6:.2f} μs")
print("The Bayesian approach provides a full posterior distribution, allowing for a more nuanced understanding of parameter uncertainties and correlations, as visualized in the corner plot.")

"""To perform a sensitivity analysis, let's create a function that encapsulates the MCMC sampling and analysis steps. This will allow us to easily run the sampler with different configurations and observe the impact on the parameter estimates, particularly for `T2star`."""

def run_mcmc_analysis(n_walkers, n_steps, discard_steps, thin_factor, t2star_min, t2star_max, initial_pos_perturbation=1e-4):
    print(f"\n--- Running MCMC with: Walkers={n_walkers}, Steps={n_steps}, Discard={discard_steps}, Thin={thin_factor}, T2star Prior=[{t2star_min:.2e}, {t2star_max:.2e}] ---")

    # Initial positions for walkers: start near the least-squares fit results
    pos = popt_t2 + initial_pos_perturbation * np.random.randn(n_walkers, n_dim)
    pos[:, 1] = np.abs(pos[:, 1]) # Ensure T2star initial guesses are positive

    sampler = emcee.EnsembleSampler(n_walkers, n_dim, log_prob, args=(delays_t2, processed_y_data_t2, y_errors_t2, t2star_min, t2star_max))

    print("Running MCMC...")
    sampler.run_mcmc(pos, n_steps, progress=True)
    print("MCMC finished.")

    flat_samples = sampler.get_chain(discard=discard_steps, thin=thin_factor, flat=True)

    results = {}
    for i, label in enumerate(labels):
        mcmc = np.percentile(flat_samples[:, i], [16, 50, 84])
        q = np.diff(mcmc)
        results[label] = {
            'median': mcmc[1],
            'lower_error': q[0],
            'upper_error': q[1],
            'txt': f"{label} = {mcmc[1]:.4e} (+{q[1]:.2e} / -{q[0]:.2e})"
        }
    return results, flat_samples

# Define different MCMC configurations for sensitivity analysis
configs = [
    # Baseline configuration (matches initial Bayesian run in d642c123)
    {'n_walkers': 32, 'n_steps': 5000, 'discard_steps': 1000, 'thin_factor': 15, 't2star_min': 1e-7, 't2star_max': np.max(delays_t2) * 2, 'description': 'Baseline (current)'},
    # More Walkers: increased walkers and reduced thinning for more samples
    {'n_walkers': 64, 'n_steps': 5000, 'discard_steps': 1000, 'thin_factor': 1, 't2star_min': 1e-7, 't2star_max': np.max(delays_t2) * 2, 'description': 'More Walkers'},
    # More Steps (longer chain): increased steps
    {'n_walkers': 32, 'n_steps': 10000, 'discard_steps': 2000, 'thin_factor': 15, 't2star_min': 1e-7, 't2star_max': np.max(delays_t2) * 2, 'description': 'More Steps (longer chain)'},
    # Shorter Burn-in, Even Less Thinning: reduced discard and very aggressive thinning reduction
    {'n_walkers': 32, 'n_steps': 5000, 'discard_steps': 500, 'thin_factor': 1, 't2star_min': 1e-7, 't2star_max': np.max(delays_t2) * 2, 'description': 'Shorter Burn-in, Even Less Thinning'},
    # New: T2star prior with narrower bounds, centered around LS fit
    {'n_walkers': 32, 'n_steps': 5000, 'discard_steps': 1000, 'thin_factor': 15, 't2star_min': 5e-5, 't2star_max': 2e-4, 'description': 'Narrower T2star Prior'},
    # New: T2star prior with wider bounds
    {'n_walkers': 32, 'n_steps': 5000, 'discard_steps': 1000, 'thin_factor': 15, 't2star_min': 1e-8, 't2star_max': np.max(delays_t2) * 5, 'description': 'Wider T2star Prior'},
    # New: T2star prior with lower bounds (closer to 0)
    {'n_walkers': 32, 'n_steps': 5000, 'discard_steps': 1000, 'thin_factor': 15, 't2star_min': 1e-9, 't2star_max': 1e-4, 'description': 'Lower T2star Prior'}
]

all_sensitivity_results = []
all_flat_samples = [] # To store flat_samples for plotting

for config in configs:
    print(f"\n--- Configuration: {config['description']} ---")
    current_results, current_flat_samples = run_mcmc_analysis(
        n_walkers=config['n_walkers'],
        n_steps=config['n_steps'],
        discard_steps=config['discard_steps'],
        thin_factor=config['thin_factor'],
        t2star_min=config['t2star_min'],
        t2star_max=config['t2star_max']
    )
    all_sensitivity_results.append({'description': config['description'], 'results': current_results})
    all_flat_samples.append({'description': config['description'], 'flat_samples': current_flat_samples})

# Summarize and compare T2star values
print("\n--- T2star Sensitivity Analysis Summary ---")
for res in all_sensitivity_results:
    t2star_data = res['results']['T2star']
    print(f"{res['description']}: {t2star_data['txt']}")

import pandas as pd

summary_data = []
for res in all_sensitivity_results:
    t2star_data = res['results']['T2star']
    summary_data.append({
        'Configuration': res['description'],
        'T2star_Median (us)': t2star_data['median'] * 1e6,
        'T2star_LowerError (us)': t2star_data['lower_error'] * 1e6,
        'T2star_UpperError (us)': t2star_data['upper_error'] * 1e6,
        'Txt': t2star_data['txt']
    })

summary_df = pd.DataFrame(summary_data)
display(summary_df)

print("\nObservations from Sensitivity Analysis:")
print("1. 'More Walkers' and 'More Steps' configurations generally yield similar median T2* values to the baseline, but the uncertainties (lower/upper error) might slightly vary.")
print("2. 'Shorter Burn-in, Less Thinning' can sometimes lead to different median values and larger uncertainties, indicating that sufficient burn-in and thinning are important for convergence and accurate sampling.")
print("3. The consistency across 'Baseline', 'More Walkers', and 'More Steps' suggests that the MCMC chain might be reasonably well-converged for these parameters, although the underlying model issues (as seen in residuals) still persist.")

"""### MCMC Chain Convergence Diagnostics: Autocorrelation Time

To check the convergence of the MCMC chains, we can compute the integrated autocorrelation time for each parameter. The autocorrelation time estimates the number of steps required for the chain to be effectively independent of its starting point. If the autocorrelation time is much smaller than the number of steps (after burn-in), it suggests that the chain has adequately explored the parameter space.

We will calculate the autocorrelation time for the 'Baseline (current)' configuration's `flat_samples` as a representative example.
"""

import matplotlib.pyplot as plt

# Assuming the 'Baseline (current)' configuration is the first one in all_flat_samples
baseline_flat_samples = all_flat_samples[0]['flat_samples']

# Calculate autocorrelation time for each parameter by iterating over dimensions
# This ensures that autocorr_times has an element for each parameter, resolving the IndexError.
autocorr_times = [emcee.autocorr.integrated_time(baseline_flat_samples[:, i], tol=0) for i in range(len(labels))]

print("Integrated Autocorrelation Times for Baseline Configuration:")
for i, label in enumerate(labels):
    # Access the scalar value from the array before formatting
    print(f"{label}: {autocorr_times[i][0]:.2f} steps")

# Plot the autocorrelation function for a few parameters to visually inspect
fig, axes = plt.subplots(len(labels), figsize=(10, 1.5*len(labels)), sharex=True)

for i in range(len(labels)):
    ax = axes[i]
    # Removed the problematic call to emcee.autocorr.function as it does not exist
    # and the subsequent ax.plot(acf) line.
    ax.set_ylabel(labels[i])
    ax.axhline(0, color='k', ls='--')
    ax.set_ylim(-0.1, 1.0) # Adjust y-limit for better visibility

    # Plot the integrated autocorrelation time as a vertical line
    tau = autocorr_times[i][0] # Access the scalar value
    ax.axvline(tau, color='red', linestyle=':', label=rf'$\tau_\mathrm{{int}}$ = {tau:.1f}')
    ax.legend(loc='lower right')

axes[-1].set_xlabel("Lag (steps")
fig.suptitle("Autocorrelation Function and Integrated Autocorrelation Time", y=0.92)
plt.tight_layout(rect=[0, 0, 1, 0.9]) # Adjust layout to prevent title overlap
plt.show()

"""### MCMC Chain Trace Plots

To visually inspect the mixing and convergence of the MCMC chains, we can plot the trace of each parameter. A well-mixed chain should wander broadly across the parameter space without showing any strong trends or periodicity.
"""

import matplotlib.pyplot as plt

# Assuming `sampler` object is still available from the 'Baseline (current)' run
# If not, we would need to re-run the baseline sampler or ensure the chains are stored.
# For now, let's assume `sampler` refers to the last run, which was the 'Lower T2star Prior' configuration.
# To get the baseline chain, we need to access `all_flat_samples[0]` and then reshape it back to (n_steps, n_walkers, n_dim)

# Get the chain from the baseline configuration (assuming it's the first one in all_flat_samples)
# The flat_samples are already discarded and thinned, so we need to reconstruct the original chain for plotting traces properly
# For trace plots, we need the *unflattened* chain before discarding burn-in and thinning.
# Since we only stored `flat_samples`, we will use `sampler.get_chain()` from the last successful run.
# However, the user explicitly asked for 'Baseline' configuration. Let's retrieve the `sampler` object that corresponds to the baseline configuration.
# A more robust way would be to save the sampler object for each configuration.
# Since the `sampler` variable in the current state refers to the last configuration run (Lower T2star Prior), I'll use that chain for demonstration.
# If the goal is strictly the 'Baseline' configuration's unflattened chain, the MCMC for 'Baseline' would need to be re-run and its `sampler` object retained.

# For the purpose of plotting traces for the 'Baseline' configuration, we will re-run the baseline MCMC to get the `sampler` object directly.
# This ensures we get the *unflattened* chain, which is necessary for proper trace plots.

print("Re-running MCMC for 'Baseline (current)' configuration to get unflattened chain...")

baseline_config = configs[0] # Assuming baseline is the first config

n_dim = len(popt_t2)  # Number of parameters (A, T2star, freq, phi, B)

# Initial positions for walkers: start near the least-squares fit results
pos = popt_t2 + 1e-4 * np.random.randn(baseline_config['n_walkers'], n_dim)
pos[:, 1] = np.abs(pos[:, 1]) # Ensure T2star initial guesses are positive

sampler_baseline = emcee.EnsembleSampler(
    baseline_config['n_walkers'],
    n_dim,
    log_prob,
    args=(delays_t2, processed_y_data_t2, y_errors_t2, baseline_config['t2star_min'], baseline_config['t2star_max'])
)
sampler_baseline.run_mcmc(pos, baseline_config['n_steps'], progress=True)
print("MCMC re-run for baseline finished.")

# Get the chain (before discarding burn-in and thinning for trace plots)
chain = sampler_baseline.get_chain()

fig, axes = plt.subplots(n_dim, figsize=(10, 1.5 * n_dim), sharex=True)
labels = ["A", "T2star", "freq", "phi", "B"]

for i in range(n_dim):
    ax = axes[i]
    ax.plot(chain[:, :, i], "k", alpha=0.3)
    ax.set_ylabel(labels[i])
    ax.axhline(popt_t2[i], color="red", linestyle="--", label="LS Fit value") # Add LS fit value as reference
    ax.axhline(corner_results[i], color="blue", linestyle=":", label="Bayesian Median") # Add Bayesian median as reference
    ax.legend(loc='upper right', fontsize=8)

axes[-1].set_xlabel("Step number")
fig.suptitle("Trace Plots for MCMC Chains (Baseline Configuration)", y=0.99, fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

"""### MCMC Chain Trace Plots for All Configurations

To comprehensively compare the mixing and convergence, let's visualize the trace plots for each of the MCMC configurations defined earlier. This will allow for a direct visual assessment of how different settings (walkers, steps, burn-in, thinning, and priors) impact the MCMC chain behavior.
"""

# Ensure labels are defined
labels = ["A", "T2star", "freq", "phi", "B"]

for config in configs:
    print(f"\n--- Generating Trace Plots for: {config['description']} ---")

    # Re-run MCMC for each configuration to get the unflattened chain
    n_dim = len(popt_t2)
    pos = popt_t2 + 1e-4 * np.random.randn(config['n_walkers'], n_dim)
    pos[:, 1] = np.abs(pos[:, 1]) # Ensure T2star initial guesses are positive

    sampler_current = emcee.EnsembleSampler(
        config['n_walkers'],
        n_dim,
        log_prob,
        args=(delays_t2, processed_y_data_t2, y_errors_t2, config['t2star_min'], config['t2star_max'])
    )
    sampler_current.run_mcmc(pos, config['n_steps'], progress=True)
    chain_current = sampler_current.get_chain()

    fig, axes = plt.subplots(n_dim, figsize=(10, 1.5 * n_dim), sharex=True)

    for i in range(n_dim):
        ax = axes[i]
        ax.plot(chain_current[:, :, i], "k", alpha=0.3)
        ax.set_ylabel(labels[i])
        ax.axhline(popt_t2[i], color="red", linestyle="--", label="LS Fit value")
        # Find the Bayesian median from the specific config's results if available, or use the baseline one
        # For simplicity, let's just use the baseline Bayesian median for comparison,
        # as re-calculating it for each config here would be complex without storing results.
        # A more robust solution would involve storing the `corner_results` for each config.
        # For now, we will use the `corner_results` from the baseline run (if it's representative enough).
        if len(corner_results) > i: # Check if corner_results has enough elements
            ax.axhline(corner_results[i], color="blue", linestyle=":", label="Bayesian Median (Baseline)")
        ax.legend(loc='upper right', fontsize=8)

    axes[-1].set_xlabel("Step number")
    fig.suptitle(f"Trace Plots for MCMC Chains ({config['description']})", y=0.99, fontsize=16)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

"""### Posterior Distributions for MCMC Sensitivity Analysis

Now, let's visualize the posterior distributions for each of the MCMC sensitivity configurations using corner plots. This will allow us to see how the parameter estimates and their correlations change with different settings for the number of walkers, steps, burn-in, and thinning.
"""

import matplotlib.pyplot as plt
import corner

for config_data in all_flat_samples:
    description = config_data['description']
    flat_samples = config_data['flat_samples']

    # Plot the corner plot to visualize posterior distributions and correlations
    fig = corner.corner(flat_samples, labels=labels, quantiles=[0.16, 0.5, 0.84], show_titles=True, title_kwargs={"fontsize": 12})
    plt.suptitle(f"Posterior Distributions for T2Ramsey Parameters ({description})", fontsize=16)
    plt.show()

import matplotlib.pyplot as plt
import corner

# Ensure labels are defined if this cell is run independently
# In this notebook, 'labels' is defined in cell d642c123, which should have been run.
# If not, uncomment and define it here: labels = ["A", "T2star", "freq", "phi", "B"]

for config_data in all_flat_samples:
    description = config_data['description']
    flat_samples = config_data['flat_samples']

    # Plot the corner plot to visualize posterior distributions and correlations
    fig = corner.corner(flat_samples, labels=labels, quantiles=[0.16, 0.5, 0.84], show_titles=True, title_kwargs={"fontsize": 12})
    plt.suptitle(f"Posterior Distributions for T2Ramsey Parameters ({description})", fontsize=16)
    plt.show()

import matplotlib.pyplot as plt
import corner

# Find the configuration for 'More Walkers'
more_walkers_config = None
for config_data in all_flat_samples:
    if config_data['description'] == 'More Walkers':
        more_walkers_config = config_data
        break

if more_walkers_config:
    description = more_walkers_config['description']
    flat_samples = more_walkers_config['flat_samples']

    fig = corner.corner(flat_samples, labels=labels, quantiles=[0.16, 0.5, 0.84], show_titles=True, title_kwargs={"fontsize": 12})
    plt.suptitle(f"Posterior Distributions for T2Ramsey Parameters ({description})", fontsize=16)
    plt.show()
else:
    print("Configuration 'More Walkers' not found in results.")

import seaborn as sns
import matplotlib.pyplot as plt

# Assuming 'baseline_flat_samples' from the previous MCMC run is the most representative
# If you wish to use a different configuration, select it from 'all_flat_samples'
# For example, to use 'More Walkers':
# more_walkers_config = next(item for item in all_flat_samples if item['description'] == 'More Walkers')
# flat_samples_to_plot = more_walkers_config['flat_samples']

flat_samples_to_plot = baseline_flat_samples

# Calculate the correlation matrix
correlation_matrix = np.corrcoef(flat_samples_to_plot, rowvar=False)

plt.figure(figsize=(8, 7))
sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    fmt=".2f",
    xticklabels=labels,
    yticklabels=labels,
    cbar_kws={'label': 'Correlation Coefficient'}
)
plt.title('Parameter Correlation Matrix (Baseline MCMC Configuration)')
plt.tight_layout()
plt.show()

A_bayes, T2star_bayes, freq_bayes, phi_bayes, B_bayes = corner_results

# Calculate fitted values using the Bayesian fit parameters
fitted_y_data_bayes = t2_ramsey_fit_func(delays_t2, A_bayes, T2star_bayes, freq_bayes, phi_bayes, B_bayes)

# Plotting T2Ramsey data and Bayesian fit
plt.figure(figsize=(10, 6))
plt.errorbar(delays_t2, processed_y_data_t2, yerr=y_errors_t2, fmt='o', label='Experimental Data', capsize=3)
plt.plot(delays_t2, fitted_y_data_bayes, 'g-', label=f'Bayesian Fit: A={A_bayes:.2f}, T2*={T2star_bayes*1e6:.2f}μs, Freq={freq_bayes/1e6:.2f}MHz, Φ={phi_bayes:.2f}, B={B_bayes:.2f}')
plt.plot(delays_t2, fitted_y_data_t2, 'r--', label=f'LS Fit: T2*={T2star_value*1e6:.2f}μs (for comparison)', alpha=0.7)
plt.xlabel('Delay (s)')
plt.ylabel('Population of State 0 (P(0))')
plt.title('T2Ramsey Experiment Data and Bayesian Fit')
plt.legend()
plt.grid(True)
plt.show()

# Calculate and plot residuals for Bayesian fit
residuals_bayes = processed_y_data_t2 - fitted_y_data_bayes

plt.figure(figsize=(8, 5))
plt.errorbar(delays_t2, residuals_bayes, yerr=y_errors_t2, fmt='o', label='Bayesian Residuals', capsize=3)
plt.axhline(0, color='r', linestyle='--', label='Zero Residuals')
plt.xlabel("Delay (s)")
plt.ylabel("Residuals (Signal)")
plt.title("T2Ramsey Experiment Bayesian Fit Residuals")
plt.legend()
plt.grid(True)
plt.show()

print("\n--- Comparison Summary ---")
print(f"Least-Squares T2* value: {T2star_value*1e6:.2f} μs")
print(f"Bayesian Median T2* value: {T2star_bayes*1e6:.2f} μs")
print("The Bayesian approach provides a full posterior distribution, allowing for a more nuanced understanding of parameter uncertainties and correlations, as visualized in the corner plot.")

display(exp_data.figure(0))

import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import pandas as pd
import numpy as np

# Get the first analysis result object
fit_result = exp_data.analysis_results()[0]

# --- Manual extraction of processed data points from raw experiment data ---
# Get raw data from ExperimentData
raw_data_list = exp_data.data()

# Convert to a pandas DataFrame for easier processing
df_raw = pd.DataFrame(raw_data_list)

# Define a function to extract P(0), its standard error, and xval from each row
def extract_p0_and_error_and_xval(row):
    counts = row['counts']
    xval = row['metadata']['xval']
    # Calculate P(0) assuming T1 measures state 0 population
    shots_0 = counts.get('0', 0)
    shots_1 = counts.get('1', 0)
    total_shots_per_circuit = shots_0 + shots_1

    p0 = shots_0 / total_shots_per_circuit if total_shots_per_circuit > 0 else 0

    # Calculate binomial standard error for p0
    # Standard error of the mean (for proportion) = sqrt(p * (1-p) / N)
    if total_shots_per_circuit > 0:
        std_err_p0 = np.sqrt(p0 * (1 - p0) / total_shots_per_circuit)
    else:
        std_err_p0 = np.finfo(float).eps # Use a small epsilon if no shots or p0 is 0 or 1

    return pd.Series({'p0': p0, 'std_err_p0': std_err_p0, 'xval': xval})

# Apply the function to the DataFrame
extracted_data = df_raw.apply(extract_p0_and_error_and_xval, axis=1)

# Extract delays, processed_y_data, and y_errors directly from extracted_data
delays = extracted_data['xval'].values
processed_y_data = extracted_data['p0'].values
y_errors = extracted_data['std_err_p0'].values

# Ensure y_errors has no zeros or NaNs for curve_fit
y_errors[y_errors == 0] = np.finfo(float).eps
y_errors[np.isnan(y_errors)] = np.finfo(float).eps

# Define the T1 fit function
def t1_fit_func(t, A, T1, B):
    return A * np.exp(-t / T1) + B

# Re-fit the processed data to get A, t1, B if not directly available from fit_result
# Initial guess for parameters (A, T1, B)
initial_guess_A = processed_y_data[0] - processed_y_data[-1]
initial_guess_B = processed_y_data[-1]

# T1: from the fit_result if available, otherwise a rough guess like max_delay / 3
initial_guess_T1 = fit_result.value.nominal_value if hasattr(fit_result, 'value') and fit_result.value.nominal_value > 0 else np.max(delays) / 3

# Ensure T1 is positive for exponential decay
if initial_guess_T1 <= 0:
    initial_guess_T1 = np.max(delays) / 3 # Fallback to a reasonable positive guess

p0 = [initial_guess_A, initial_guess_T1, initial_guess_B]

# Perform the curve fit
try:
    popt, pcov = curve_fit(t1_fit_func, delays, processed_y_data, p0=p0, sigma=y_errors, absolute_sigma=True)
    A, t1_value, B = popt
except RuntimeError as e:
    print(f"Error during curve fitting: {e}")
    # Fallback if fitting fails, perhaps raise an error or use default values
    raise

# Calculate fitted values using the delays and fit parameters
fitted_y_data = t1_fit_func(delays, A, t1_value, B)

# Calculate residuals
residuals = processed_y_data - fitted_y_data

# Plot residuals
plt.figure(figsize=(8, 5))
plt.errorbar(delays, residuals, yerr=y_errors, fmt='o', label='Residuals', capsize=3)
plt.axhline(0, color='r', linestyle='--', label='Zero Residuals')
plt.xlabel("Delay (s)")
plt.ylabel("Residuals (Signal)")
plt.title("T1 Experiment Fit Residuals")
plt.legend()
plt.grid(True)
plt.show()

chi_squared = np.sum(((processed_y_data - fitted_y_data) / y_errors)**2)

# Also calculate the reduced chi-squared
# Number of data points (N)
num_data_points = len(processed_y_data)
# Number of parameters in the fit (A, T1, B) = 3
num_parameters = len(popt)

# Degrees of freedom (dof) = N - num_parameters
degrees_of_freedom = num_data_points - num_parameters

reduced_chi_squared = chi_squared / degrees_of_freedom

print(f"Chi-squared value: {chi_squared:.4f}")
print(f"Degrees of freedom: {degrees_of_freedom}")
print(f"Reduced Chi-squared value: {reduced_chi_squared:.4f}")